// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwlkfxqmjhzywwcqclfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bGtmeHFtamh6eXd3Y3FjbGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjIzMTYsImV4cCI6MjA2OTM5ODMxNn0.v-U41B2NXowM2e9YButpmwkRwOTEg1XP2ySoDuMRoK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});